name: build-macos

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
  
jobs:
  build-osx:
    runs-on: macos-10.15
    steps:
    - name: getOF
      uses: robinraju/release-downloader@v1.4
      with:
        repository: "openframeworks/openFrameworks"
        latest: true
        fileName: "*_osx_release.zip"
        out-file-path: "downloads"
    - name: list
      run: ls downloads
    - name: installOF
      run: 
          pwd -P;
          res=$(find ./downloads -name "*_osx_release.zip" | head -1);
          unzip $res -d openFrameworks/; 
          cd openFrameworks;
          mv $(ls) ../temp;
          cd ..;
          rm -rf openFrameworks;
          mv temp openFrameworks;
          cd openFrameworks;
          echo "-----ls openFrameworks-----";
          pwd -P;
          ls;
          repoName=$(basename ${{ github.repository }});
          echo "REPO_NAME=$repoName" >> $GITHUB_ENV;
          echo "REPO_DOWNLOAD_PATH=openFrameworks/addons/$repoName" >> $GITHUB_ENV;
          echo "GITHUB_WORKSPACE $GITHUB_WORKSPACE";
    - uses: actions/checkout@v2
      with:
        path: ${{ env.REPO_DOWNLOAD_PATH }}
    - name: generate Project
      run: OF_PATH=$( cd "openFrameworks" ; pwd -P );
           cd $OF_PATH ;
           echo "----ofPath---";
           echo $OF_PATH ;
           ls ;
           ls addons ;
           echo "-------";
           ls addons/ofxPlaybackGui ;
           ./projectGenerator/projectGenerator.app/Contents/Resources/app/app/projectGenerator -o"$OF_PATH" -p"osx" -t"" "$OF_PATH/addons/${{ env.REPO_NAME }}/example";
      
    
#    - name: Build
#      env:
#        DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
#        SDKROOT: "/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
