name: build-macos

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
  
jobs:

  build-osx:
    runs-on: macos-10.15
    strategy:
        matrix:
          cfg:
          - {target: osx, opt: ""}
          - {target: osx, opt: "makefiles"}
    env:
      TARGET: ${{matrix.cfg.target}}
      OPT: ${{matrix.cfg.opt}}
    steps:
    - uses: actions/checkout@v2
    - name: getOF
      uses: robinraju/release-downloader@v1.4
      with:
        repository: "openframeworks/openFrameworks"
        latest: true
        fileName: "*_osx_release.zip"
        out-file-path: "downloads"
    - name: installOF
      run: 
          mkdir ~/openFrameworks
          cd $GITHUB_WORKSPACE/downloads
          res=$(find . -name "*_osx_release.zip" | head -1)
          unzip $res -d ~/openFrameworks

#    - name: Build
#      env:
#        DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
#        SDKROOT: "/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
